### PR TITLE
Add Pow Signal Monitoring and list of dictionaries for addresses and methods

### PR DESCRIPTION
**Pull request by robertjitaru**

### CODE REVIEW

**Review by PBillingsby — APPROVED** [review]
Tested in a test server. LGTM! Nice work @Rodebrechtd 

Screenshot 2024-10-01 at 4 38 53 PM

**Comment by galaxyxtwo** [comment]
@Rodebrechtd @PBillingsby do we want this bot in the same "Partner-alarms" discord channel?

**Comment by PBillingsby** [comment]
> @Rodebrechtd @PBillingsby do we want this bot in the same "Partner-alarms" discord channel?

Given that it is the same PoW notification bot with more context, i'd say yes. I think it should only be visible to the team and advocates. Open to suggestions though!

**Comment by galaxyxtwo** [comment]
awesome! Lets see how it looks once implemented.

**Comment by galaxyxtwo** [comment]
@Rodebrechtd do I need to add a webhook url for POW_MONITORING_WEBHOOK? It looks like thats the secret the bot is calling?

**Comment by robertjitaru** [comment]
@galaxyxtwo, I'm using the previous webhook. I don't need a new one since the context is the same. Thanks!

**Pull request merged**
