### PR TITLE
Add POW Monitoring Discord Bot

### PR DESCRIPTION
**Pull request by robertjitaru**

### CODE REVIEW

**Comment by galaxyxtwo** [comment]
tysm. One question, noticed that OSS_DISCORD_WEBHOOK is imported and used. Is there a need to use this variable for the "partners-alarm" channel?

**Comment by robertjitaru** [comment]
@galaxyxtwo, no. It is used for open-source channel. The OSS_DISCORD_WEBHOOK variable is part of the renaming refactoring to accommodate additional use cases; it was originally named DISCORD_WEBHOOK but now we have more webhooks

**Comment by galaxyxtwo** [comment]
understood. thanks.

**Review by galaxyxtwo — COMMENTED** [review]
approved

**Pull request merged**
